# python main.py --model GCN --dataset Cora --lr 5e-3 --weight_decay 1e-3 --dropout 0.0 --num_layers 2
# python main.py --model GCN --dataset CiteSeer --lr 1e-3 --weight_decay 1e-2 --dropout 0.3 --num_layers 2
# python main.py --model GCN --dataset PubMed --lr 5e-2 --weight_decay 5e-5 --dropout 0.3 --num_layers 2
# python main.py --model GCN --dataset CoraFull --lr 5e-3 --weight_decay 1e-3 --dropout 0.0 --num_layers 2
# python main.py --model GCN --dataset CS --lr 5e-3 --weight_decay 5e-4 --dropout 0.1 --num_layers 2
# python main.py --model GCN --dataset Physics --lr 1e-2 --weight_decay 1e-4 --dropout 0.5 --num_layers 2
# python main.py --model GCN --dataset Cornell --lr 5e-2 --weight_decay 5e-3 --dropout 0.1 --num_layers 2
# python main.py --model GCN --dataset Texas --lr 5e-2 --weight_decay 1e-5 --dropout 0.0 --num_layers 8
# python main.py --model GCN --dataset Wisconsin --lr 5e-2 --weight_decay 1e-2 --dropout 0.0 --num_layers 2
# python main.py --model GCN --dataset Chameleon --lr 5e-3 --weight_decay 0.0 --dropout 0.0 --num_layers 2
# python main.py --model GCN --dataset Squirrel --lr 5e-2 --weight_decay 0.0 --dropout 0.0 --num_layers 2
# python main.py --model GCN --dataset Actor --lr 5e-3 --weight_decay 1e-3 --dropout 0.5 --num_layers 2
# python main.py --model GCN --dataset WikiCS --lr 5e-2 --weight_decay 1e-5 --dropout 0.5 --num_layers 2
# python main.py --model GCN --dataset ogbn-arxiv --lr 1e-2 --weight_decay 1e-5 --dropout 0.1 --num_layers 4