# python main.py --model Linear --dataset Cora --lr 1e-2 --weight_decay 5e-3 --dropout 0.5
# python main.py --model Linear --dataset CiteSeer --lr 5e-3 --weight_decay 1e-2 --dropout 0.5
# python main.py --model Linear --dataset PubMed --lr 5e-2 --weight_decay 1e-5 --dropout 0.1
# python main.py --model Linear --dataset CoraFull --lr 5e-2 --weight_decay 5e-4 --dropout 0.3
# python main.py --model Linear --dataset CS --lr 5e-3 --weight_decay 5e-5 --dropout 0.5
# python main.py --model Linear --dataset Physics --lr 5e-3 --weight_decay 1e-4 --dropout 0.0
# python main.py --model Linear --dataset Cornell --lr 5e-2 --weight_decay 5e-3 --dropout 0.3
# python main.py --model Linear --dataset Texas --lr 5e-2 --weight_decay 1e-2 --dropout 0.5
# python main.py --model Linear --dataset Wisconsin --lr 5e-2 --weight_decay 5e-3 --dropout 0.1
# python main.py --model Linear --dataset Chameleon --lr 5e-3 --weight_decay 1e-5 --dropout 0.5
# python main.py --model Linear --dataset Squirrel --lr 5e-2 --weight_decay 1e-2 --dropout 0.0
# python main.py --model Linear --dataset Actor --lr 5e-2 --weight_decay 5e-4 --dropout 0.0
# python main.py --model Linear --dataset WikiCS --lr 5e-2 --weight_decay 5e-5 --dropout 0.3
# python main.py --model Linear --dataset ogbn-arxiv --lr 5e-2 --weight_decay 1e-5 --dropout 0.5