python main.py --model MLP --dataset Cora --lr 5e-3 --weight_decay 1e-2 --dropout 0.1 --num_layers 2
python main.py --model MLP --dataset CiteSeer --lr 5e-3 --weight_decay 1e-4 --dropout 0.5 --num_layers 2
python main.py --model MLP --dataset PubMed --lr 5e-2 --weight_decay 1e-4 --dropout 0.1 --num_layers 2
python main.py --model MLP --dataset CoraFull --lr 1e-2 --weight_decay 0.0 --dropout 0.5 --num_layers 2
python main.py --model MLP --dataset CS --lr 1e-2 --weight_decay 0.0 --dropout 0.5 --num_layers 2
python main.py --model MLP --dataset Physics --lr 5e-3 --weight_decay 5e-5 --dropout 0.5 --num_layers 2
python main.py --model MLP --dataset Cornell --lr 5e-2 --weight_decay 1e-3 --dropout 0.5 --num_layers 2
python main.py --model MLP --dataset Texas --lr 5e-2 --weight_decay 1e-2 --dropout 0.3 --num_layers 2
python main.py --model MLP --dataset Wisconsin --lr 1e-2 --weight_decay 5e-3 --dropout 0.5 --num_layers 2
python main.py --model MLP --dataset Chameleon --lr 5e-2 --weight_decay 0.0 --dropout 0.5 --num_layers 2
python main.py --model MLP --dataset Squirrel --lr 5e-2 --weight_decay 1e-2 --dropout 0.0 --num_layers 2
python main.py --model MLP --dataset Actor --lr 5e-3 --weight_decay 1e-2 --dropout 0.5 --num_layers 4
python main.py --model MLP --dataset WikiCS --lr 5e-2 --weight_decay 5e-4 --dropout 0.3 --num_layers 2
python main.py --model MLP --dataset ogbn-arxiv --lr 5e-3 --weight_decay 1e-4 --dropout 0.1 --num_layers 4